spring:
  data:
    mongodb:
      uri: mongodb://<your username>:<your password>@localhost:27017/<your db>?authSource=admin
      
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoOperations: DEBUG
